import mysql.connector


class Mysql_connector:

        try:
            connection = mysql.connector.connect(host="localhost", user="root", passwd="Ayuagr01", database="pythondb")
            mycursor = connection.cursor()

        except Exception as e:
            print(e)


